//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RibbonDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RibbonDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap alert32 {
            get {
                object obj = ResourceManager.GetObject("alert32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap aligncenter16 {
            get {
                object obj = ResourceManager.GetObject("aligncenter16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alignjustify16 {
            get {
                object obj = ResourceManager.GetObject("alignjustify16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alignleft16 {
            get {
                object obj = ResourceManager.GetObject("alignleft16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alignright16 {
            get {
                object obj = ResourceManager.GetObject("alignright16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrange32 {
            get {
                object obj = ResourceManager.GetObject("arrange32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrangebringfront16 {
            get {
                object obj = ResourceManager.GetObject("arrangebringfront16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrangebringfront32 {
            get {
                object obj = ResourceManager.GetObject("arrangebringfront32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrangedown16 {
            get {
                object obj = ResourceManager.GetObject("arrangedown16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrangesendback16 {
            get {
                object obj = ResourceManager.GetObject("arrangesendback16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrangeup16 {
            get {
                object obj = ResourceManager.GetObject("arrangeup16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap barcode16 {
            get {
                object obj = ResourceManager.GetObject("barcode16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap barcode32 {
            get {
                object obj = ResourceManager.GetObject("barcode32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bold16 {
            get {
                object obj = ResourceManager.GetObject("bold16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap borderall16 {
            get {
                object obj = ResourceManager.GetObject("borderall16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap borderbottom {
            get {
                object obj = ResourceManager.GetObject("borderbottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap borderbottom16 {
            get {
                object obj = ResourceManager.GetObject("borderbottom16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap borderbottomdouble16 {
            get {
                object obj = ResourceManager.GetObject("borderbottomdouble16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap borderbottomthick {
            get {
                object obj = ResourceManager.GetObject("borderbottomthick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bordereffect1 {
            get {
                object obj = ResourceManager.GetObject("bordereffect1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bordereffect2 {
            get {
                object obj = ResourceManager.GetObject("bordereffect2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bordereffect3 {
            get {
                object obj = ResourceManager.GetObject("bordereffect3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bordereffect4 {
            get {
                object obj = ResourceManager.GetObject("bordereffect4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap borderin16 {
            get {
                object obj = ResourceManager.GetObject("borderin16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap borderleft16 {
            get {
                object obj = ResourceManager.GetObject("borderleft16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bordermiddlehorizontal {
            get {
                object obj = ResourceManager.GetObject("bordermiddlehorizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bordermiddlevertical {
            get {
                object obj = ResourceManager.GetObject("bordermiddlevertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bordernone16 {
            get {
                object obj = ResourceManager.GetObject("bordernone16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap borderout16 {
            get {
                object obj = ResourceManager.GetObject("borderout16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap borderright16 {
            get {
                object obj = ResourceManager.GetObject("borderright16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap borderthick {
            get {
                object obj = ResourceManager.GetObject("borderthick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bordertop16 {
            get {
                object obj = ResourceManager.GetObject("bordertop16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap borderupandbottom16 {
            get {
                object obj = ResourceManager.GetObject("borderupandbottom16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap brightness32 {
            get {
                object obj = ResourceManager.GetObject("brightness32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel32 {
            get {
                object obj = ResourceManager.GetObject("cancel32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap capitalletter16 {
            get {
                object obj = ResourceManager.GetObject("capitalletter16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap capitalletter32 {
            get {
                object obj = ResourceManager.GetObject("capitalletter32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap casing16 {
            get {
                object obj = ResourceManager.GetObject("casing16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap casing32 {
            get {
                object obj = ResourceManager.GetObject("casing32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cellcenterbottom16 {
            get {
                object obj = ResourceManager.GetObject("cellcenterbottom16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cellcentermiddle16 {
            get {
                object obj = ResourceManager.GetObject("cellcentermiddle16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cellcentertop16 {
            get {
                object obj = ResourceManager.GetObject("cellcentertop16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cellleftbottom {
            get {
                object obj = ResourceManager.GetObject("cellleftbottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cellleftmiddle16 {
            get {
                object obj = ResourceManager.GetObject("cellleftmiddle16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap celllefttop16 {
            get {
                object obj = ResourceManager.GetObject("celllefttop16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cellrightbottom16 {
            get {
                object obj = ResourceManager.GetObject("cellrightbottom16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cellrightmiddle16 {
            get {
                object obj = ResourceManager.GetObject("cellrightmiddle16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cellrighttop16 {
            get {
                object obj = ResourceManager.GetObject("cellrighttop16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart16 {
            get {
                object obj = ResourceManager.GetObject("chart16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart32 {
            get {
                object obj = ResourceManager.GetObject("chart32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chartdraw32 {
            get {
                object obj = ResourceManager.GetObject("chartdraw32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clipart32 {
            get {
                object obj = ResourceManager.GetObject("clipart32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clock3e {
            get {
                object obj = ResourceManager.GetObject("clock3e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close16 {
            get {
                object obj = ResourceManager.GetObject("close16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close32 {
            get {
                object obj = ResourceManager.GetObject("close32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap contactadd32 {
            get {
                object obj = ResourceManager.GetObject("contactadd32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap contrast32 {
            get {
                object obj = ResourceManager.GetObject("contrast32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy16 {
            get {
                object obj = ResourceManager.GetObject("copy16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copyformat16 {
            get {
                object obj = ResourceManager.GetObject("copyformat16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copyformat3 {
            get {
                object obj = ResourceManager.GetObject("copyformat3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cover16 {
            get {
                object obj = ResourceManager.GetObject("cover16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cover32 {
            get {
                object obj = ResourceManager.GetObject("cover32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut16 {
            get {
                object obj = ResourceManager.GetObject("cut16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap datetime16 {
            get {
                object obj = ResourceManager.GetObject("datetime16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap decreasefont16 {
            get {
                object obj = ResourceManager.GetObject("decreasefont16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap decreasefont23 {
            get {
                object obj = ResourceManager.GetObject("decreasefont23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap decreasetab16 {
            get {
                object obj = ResourceManager.GetObject("decreasetab16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete16 {
            get {
                object obj = ResourceManager.GetObject("delete16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete32 {
            get {
                object obj = ResourceManager.GetObject("delete32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deleteclipboard16 {
            get {
                object obj = ResourceManager.GetObject("deleteclipboard16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap drawtools32 {
            get {
                object obj = ResourceManager.GetObject("drawtools32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap erase16 {
            get {
                object obj = ResourceManager.GetObject("erase16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eraseformat16 {
            get {
                object obj = ResourceManager.GetObject("eraseformat16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap excelsheet32 {
            get {
                object obj = ResourceManager.GetObject("excelsheet32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exclamation32 {
            get {
                object obj = ResourceManager.GetObject("exclamation32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap favorites32 {
            get {
                object obj = ResourceManager.GetObject("favorites32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fill16 {
            get {
                object obj = ResourceManager.GetObject("fill16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fill32 {
            get {
                object obj = ResourceManager.GetObject("fill32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter32 {
            get {
                object obj = ResourceManager.GetObject("filter32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find32 {
            get {
                object obj = ResourceManager.GetObject("find32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap first16 {
            get {
                object obj = ResourceManager.GetObject("first16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fliphorizontal16 {
            get {
                object obj = ResourceManager.GetObject("fliphorizontal16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flipvertical16 {
            get {
                object obj = ResourceManager.GetObject("flipvertical16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap font32 {
            get {
                object obj = ResourceManager.GetObject("font32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fontcolor16 {
            get {
                object obj = ResourceManager.GetObject("fontcolor16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap footer {
            get {
                object obj = ResourceManager.GetObject("footer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap footer16 {
            get {
                object obj = ResourceManager.GetObject("footer16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap footer32 {
            get {
                object obj = ResourceManager.GetObject("footer32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap formula16 {
            get {
                object obj = ResourceManager.GetObject("formula16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap formula32 {
            get {
                object obj = ResourceManager.GetObject("formula32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap formula321 {
            get {
                object obj = ResourceManager.GetObject("formula321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fx32 {
            get {
                object obj = ResourceManager.GetObject("fx32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap goforward16 {
            get {
                object obj = ResourceManager.GetObject("goforward16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap group16 {
            get {
                object obj = ResourceManager.GetObject("group16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap header16 {
            get {
                object obj = ResourceManager.GetObject("header16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap header32 {
            get {
                object obj = ResourceManager.GetObject("header32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap headerandfooter32 {
            get {
                object obj = ResourceManager.GetObject("headerandfooter32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help16 {
            get {
                object obj = ResourceManager.GetObject("help16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap highlight16 {
            get {
                object obj = ResourceManager.GetObject("highlight16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap home16 {
            get {
                object obj = ResourceManager.GetObject("home16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap home32 {
            get {
                object obj = ResourceManager.GetObject("home32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap horizontalspacing32 {
            get {
                object obj = ResourceManager.GetObject("horizontalspacing32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image32 {
            get {
                object obj = ResourceManager.GetObject("image32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imageeffect1 {
            get {
                object obj = ResourceManager.GetObject("imageeffect1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap increasefont16 {
            get {
                object obj = ResourceManager.GetObject("increasefont16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap increasefont32 {
            get {
                object obj = ResourceManager.GetObject("increasefont32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap increasefont321 {
            get {
                object obj = ResourceManager.GetObject("increasefont321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap increasetab16 {
            get {
                object obj = ResourceManager.GetObject("increasetab16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap insertobject16 {
            get {
                object obj = ResourceManager.GetObject("insertobject16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap italic16 {
            get {
                object obj = ResourceManager.GetObject("italic16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap last16 {
            get {
                object obj = ResourceManager.GetObject("last16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap library32 {
            get {
                object obj = ResourceManager.GetObject("library32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap line16 {
            get {
                object obj = ResourceManager.GetObject("line16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap linecolor16 {
            get {
                object obj = ResourceManager.GetObject("linecolor16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap linespacing16 {
            get {
                object obj = ResourceManager.GetObject("linespacing16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap linethru16 {
            get {
                object obj = ResourceManager.GetObject("linethru16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap link16 {
            get {
                object obj = ResourceManager.GetObject("link16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap link32 {
            get {
                object obj = ResourceManager.GetObject("link32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lookup16 {
            get {
                object obj = ResourceManager.GetObject("lookup16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap multilevellist16 {
            get {
                object obj = ResourceManager.GetObject("multilevellist16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new16 {
            get {
                object obj = ResourceManager.GetObject("new16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next16 {
            get {
                object obj = ResourceManager.GetObject("next16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ok32 {
            get {
                object obj = ResourceManager.GetObject("ok32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ol16 {
            get {
                object obj = ResourceManager.GetObject("ol16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap open16 {
            get {
                object obj = ResourceManager.GetObject("open16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap open32 {
            get {
                object obj = ResourceManager.GetObject("open32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pagefill16 {
            get {
                object obj = ResourceManager.GetObject("pagefill16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pagefill32 {
            get {
                object obj = ResourceManager.GetObject("pagefill32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pagejump16 {
            get {
                object obj = ResourceManager.GetObject("pagejump16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pagejump32 {
            get {
                object obj = ResourceManager.GetObject("pagejump32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pagenumber16 {
            get {
                object obj = ResourceManager.GetObject("pagenumber16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pagenumber32 {
            get {
                object obj = ResourceManager.GetObject("pagenumber32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pagerestricted32 {
            get {
                object obj = ResourceManager.GetObject("pagerestricted32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap palette16 {
            get {
                object obj = ResourceManager.GetObject("palette16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paly32 {
            get {
                object obj = ResourceManager.GetObject("paly32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paragraph16 {
            get {
                object obj = ResourceManager.GetObject("paragraph16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste16 {
            get {
                object obj = ResourceManager.GetObject("paste16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste32 {
            get {
                object obj = ResourceManager.GetObject("paste32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pasteall16 {
            get {
                object obj = ResourceManager.GetObject("pasteall16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preview32 {
            get {
                object obj = ResourceManager.GetObject("preview32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap previous16 {
            get {
                object obj = ResourceManager.GetObject("previous16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap property32 {
            get {
                object obj = ResourceManager.GetObject("property32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap quickitems16 {
            get {
                object obj = ResourceManager.GetObject("quickitems16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap quickitems32 {
            get {
                object obj = ResourceManager.GetObject("quickitems32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap redo16 {
            get {
                object obj = ResourceManager.GetObject("redo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refreshall32 {
            get {
                object obj = ResourceManager.GetObject("refreshall32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refreshdocument32 {
            get {
                object obj = ResourceManager.GetObject("refreshdocument32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap regional32 {
            get {
                object obj = ResourceManager.GetObject("regional32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removelink16 {
            get {
                object obj = ResourceManager.GetObject("removelink16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap replace16 {
            get {
                object obj = ResourceManager.GetObject("replace16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rotateclockw16 {
            get {
                object obj = ResourceManager.GetObject("rotateclockw16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rotateclockw32 {
            get {
                object obj = ResourceManager.GetObject("rotateclockw32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rotatecounterclockw16 {
            get {
                object obj = ResourceManager.GetObject("rotatecounterclockw16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save32 {
            get {
                object obj = ResourceManager.GetObject("save32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap searchweb {
            get {
                object obj = ResourceManager.GetObject("searchweb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select16 {
            get {
                object obj = ResourceManager.GetObject("select16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select32 {
            get {
                object obj = ResourceManager.GetObject("select32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap selectall16 {
            get {
                object obj = ResourceManager.GetObject("selectall16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shapecurve16 {
            get {
                object obj = ResourceManager.GetObject("shapecurve16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shapeellipse16 {
            get {
                object obj = ResourceManager.GetObject("shapeellipse16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shapes32 {
            get {
                object obj = ResourceManager.GetObject("shapes32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shapesquare16 {
            get {
                object obj = ResourceManager.GetObject("shapesquare16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap signature32 {
            get {
                object obj = ResourceManager.GetObject("signature32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap signatureline16 {
            get {
                object obj = ResourceManager.GetObject("signatureline16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap signatureline32 {
            get {
                object obj = ResourceManager.GetObject("signatureline32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap smartart16 {
            get {
                object obj = ResourceManager.GetObject("smartart16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap smartart32 {
            get {
                object obj = ResourceManager.GetObject("smartart32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sort16 {
            get {
                object obj = ResourceManager.GetObject("sort16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap spelling16 {
            get {
                object obj = ResourceManager.GetObject("spelling16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap spelling32 {
            get {
                object obj = ResourceManager.GetObject("spelling32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sql32 {
            get {
                object obj = ResourceManager.GetObject("sql32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sqlcheck32 {
            get {
                object obj = ResourceManager.GetObject("sqlcheck32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap style16 {
            get {
                object obj = ResourceManager.GetObject("style16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap style32 {
            get {
                object obj = ResourceManager.GetObject("style32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap subindex16 {
            get {
                object obj = ResourceManager.GetObject("subindex16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap superindex16 {
            get {
                object obj = ResourceManager.GetObject("superindex16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap symbol16 {
            get {
                object obj = ResourceManager.GetObject("symbol16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap symbol32 {
            get {
                object obj = ResourceManager.GetObject("symbol32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table16 {
            get {
                object obj = ResourceManager.GetObject("table16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table32 {
            get {
                object obj = ResourceManager.GetObject("table32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap texteffect1 {
            get {
                object obj = ResourceManager.GetObject("texteffect1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textframe16 {
            get {
                object obj = ResourceManager.GetObject("textframe16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap textframe32 {
            get {
                object obj = ResourceManager.GetObject("textframe32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ul16 {
            get {
                object obj = ResourceManager.GetObject("ul16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap underline16 {
            get {
                object obj = ResourceManager.GetObject("underline16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo16 {
            get {
                object obj = ResourceManager.GetObject("undo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ungroup16 {
            get {
                object obj = ResourceManager.GetObject("ungroup16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap useradd32 {
            get {
                object obj = ResourceManager.GetObject("useradd32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wordart16 {
            get {
                object obj = ResourceManager.GetObject("wordart16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wordart32 {
            get {
                object obj = ResourceManager.GetObject("wordart32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom100_32 {
            get {
                object obj = ResourceManager.GetObject("zoom100_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom32 {
            get {
                object obj = ResourceManager.GetObject("zoom32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoomfitpage32 {
            get {
                object obj = ResourceManager.GetObject("zoomfitpage32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
