//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftLogik.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftLogik.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1downarrow {
            get {
                object obj = ResourceManager.GetObject("_1downarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1downarrow22 {
            get {
                object obj = ResourceManager.GetObject("_1downarrow22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1leftarrow {
            get {
                object obj = ResourceManager.GetObject("_1leftarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1rightarrow {
            get {
                object obj = ResourceManager.GetObject("_1rightarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1uparrow22 {
            get {
                object obj = ResourceManager.GetObject("_1uparrow22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2downarrow {
            get {
                object obj = ResourceManager.GetObject("_2downarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2leftarrow {
            get {
                object obj = ResourceManager.GetObject("_2leftarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2rightarrow {
            get {
                object obj = ResourceManager.GetObject("_2rightarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2uparrow {
            get {
                object obj = ResourceManager.GetObject("_2uparrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3uparrow {
            get {
                object obj = ResourceManager.GetObject("_3uparrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap abacus24 {
            get {
                object obj = ResourceManager.GetObject("abacus24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap admin_24 {
            get {
                object obj = ResourceManager.GetObject("admin_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlignTableCellMiddleLeftJustHS {
            get {
                object obj = ResourceManager.GetObject("AlignTableCellMiddleLeftJustHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArreterSZ {
            get {
                object obj = ResourceManager.GetObject("ArreterSZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowLeft {
            get {
                object obj = ResourceManager.GetObject("ArrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowMenu {
            get {
                object obj = ResourceManager.GetObject("ArrowMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowRight {
            get {
                object obj = ResourceManager.GetObject("ArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowUp {
            get {
                object obj = ResourceManager.GetObject("ArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueTooth {
            get {
                object obj = ResourceManager.GetObject("BlueTooth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Book_angleHS {
            get {
                object obj = ResourceManager.GetObject("Book_angleHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Book_openHS {
            get {
                object obj = ResourceManager.GetObject("Book_openHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_cancel {
            get {
                object obj = ResourceManager.GetObject("button_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Calendar241 {
            get {
                object obj = ResourceManager.GetObject("Calendar241", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Clock {
            get {
                object obj = ResourceManager.GetObject("Clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clock_24 {
            get {
                object obj = ResourceManager.GetObject("clock_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Computer {
            get {
                object obj = ResourceManager.GetObject("Computer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap computer_32 {
            get {
                object obj = ResourceManager.GetObject("computer_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Contacts24 {
            get {
                object obj = ResourceManager.GetObject("Contacts24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Control_Panel {
            get {
                object obj = ResourceManager.GetObject("Control_Panel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Critical {
            get {
                object obj = ResourceManager.GetObject("Critical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap desktop22 {
            get {
                object obj = ResourceManager.GetObject("desktop22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Diary24 {
            get {
                object obj = ResourceManager.GetObject("Diary24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DockPaneCaption_AutoHideNo {
            get {
                object obj = ResourceManager.GetObject("DockPaneCaption_AutoHideNo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DockPaneCaption_AutoHideYes {
            get {
                object obj = ResourceManager.GetObject("DockPaneCaption_AutoHideYes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DockPaneCaption_CloseDisabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneCaption_CloseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DockPaneCaption_CloseEnabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneCaption_CloseEnabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DockPaneCaption_OptionsDisabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneCaption_OptionsDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DockPaneCaption_OptionsEnabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneCaption_OptionsEnabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DockPaneStrip_CloseDisabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneStrip_CloseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DockPaneStrip_CloseEnabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneStrip_CloseEnabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DockPaneStrip_OptionsDisabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneStrip_OptionsDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DockPaneStrip_OptionsEnabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneStrip_OptionsEnabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DockPaneStrip_OverflowDisabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneStrip_OverflowDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DockPaneStrip_OverflowEnabled {
            get {
                object obj = ResourceManager.GetObject("DockPaneStrip_OverflowEnabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EcranLcd {
            get {
                object obj = ResourceManager.GetObject("EcranLcd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EcranLcd_Off {
            get {
                object obj = ResourceManager.GetObject("EcranLcd_Off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit_file_24 {
            get {
                object obj = ResourceManager.GetObject("Edit_file_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap editdelete {
            get {
                object obj = ResourceManager.GetObject("editdelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon eventlogSuccessAudit {
            get {
                object obj = ResourceManager.GetObject("eventlogSuccessAudit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon eventlogSuccessAudit1 {
            get {
                object obj = ResourceManager.GetObject("eventlogSuccessAudit1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FermerSZ {
            get {
                object obj = ResourceManager.GetObject("FermerSZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FermerSZ1 {
            get {
                object obj = ResourceManager.GetObject("FermerSZ1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filesave {
            get {
                object obj = ResourceManager.GetObject("filesave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderList24 {
            get {
                object obj = ResourceManager.GetObject("FolderList24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Generic_Document {
            get {
                object obj = ResourceManager.GetObject("Generic_Document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon keys {
            get {
                object obj = ResourceManager.GetObject("keys", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_16 {
            get {
                object obj = ResourceManager.GetObject("lock_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Locker {
            get {
                object obj = ResourceManager.GetObject("Locker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lockup {
            get {
                object obj = ResourceManager.GetObject("Lockup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LoginControl {
            get {
                object obj = ResourceManager.GetObject("LoginControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mail24 {
            get {
                object obj = ResourceManager.GetObject("Mail24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###,###,###,###.##0.
        /// </summary>
        internal static string MoneyFormat {
            get {
                return ResourceManager.GetString("MoneyFormat", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap monitor_48 {
            get {
                object obj = ResourceManager.GetObject("monitor_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavigateBar {
            get {
                object obj = ResourceManager.GetObject("NavigateBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NoImage {
            get {
                object obj = ResourceManager.GetObject("NoImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap notepad_32 {
            get {
                object obj = ResourceManager.GetObject("notepad_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Notes24 {
            get {
                object obj = ResourceManager.GetObject("Notes24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OrganizerHS {
            get {
                object obj = ResourceManager.GetObject("OrganizerHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reload {
            get {
                object obj = ResourceManager.GetObject("reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search22 {
            get {
                object obj = ResourceManager.GetObject("search22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shortcut24 {
            get {
                object obj = ResourceManager.GetObject("Shortcut24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sort_incr {
            get {
                object obj = ResourceManager.GetObject("sort_incr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SPTaskViewDesigner {
            get {
                object obj = ResourceManager.GetObject("SPTaskViewDesigner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Switch_User {
            get {
                object obj = ResourceManager.GetObject("Switch_User", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon SYS {
            get {
                object obj = ResourceManager.GetObject("SYS", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tasks24 {
            get {
                object obj = ResourceManager.GetObject("Tasks24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or Remove Button.
        /// </summary>
        internal static string TEXT_ADD_OR_REMOVE_BUTTON {
            get {
                return ResourceManager.GetString("TEXT_ADD_OR_REMOVE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TEXT_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string TEXT_BUTTON_MOVE_DOWN {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_MOVE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string TEXT_BUTTON_MOVE_UP {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_MOVE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string TEXT_BUTTON_OK {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string TEXT_BUTTON_RESET {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Buttons.
        /// </summary>
        internal static string TEXT_CONFIGURE_BUTTONS {
            get {
                return ResourceManager.GetString("TEXT_CONFIGURE_BUTTONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display buttons in this order.
        /// </summary>
        internal static string TEXT_LABEL_ORDER_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_LABEL_ORDER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Options....
        /// </summary>
        internal static string TEXT_MENU_OPTIONS {
            get {
                return ResourceManager.GetString("TEXT_MENU_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Fewer Buttons.
        /// </summary>
        internal static string TEXT_SHOW_FEWER_BUTTONS {
            get {
                return ResourceManager.GetString("TEXT_SHOW_FEWER_BUTTONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show More Buttons.
        /// </summary>
        internal static string TEXT_SHOW_MORE_BUTTONS {
            get {
                return ResourceManager.GetString("TEXT_SHOW_MORE_BUTTONS", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap TileWindowsHorizontallyHS {
            get {
                object obj = ResourceManager.GetObject("TileWindowsHorizontallyHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap touch_screen_kiosk_24 {
            get {
                object obj = ResourceManager.GetObject("touch_screen_kiosk_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap umd_red {
            get {
                object obj = ResourceManager.GetObject("umd_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_48 {
            get {
                object obj = ResourceManager.GetObject("user_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon user_group {
            get {
                object obj = ResourceManager.GetObject("user_group", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon users {
            get {
                object obj = ResourceManager.GetObject("users", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wi0054_48 {
            get {
                object obj = ResourceManager.GetObject("wi0054_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wi0111_48 {
            get {
                object obj = ResourceManager.GetObject("wi0111_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wi0122_48 {
            get {
                object obj = ResourceManager.GetObject("wi0122_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap world_24_hot {
            get {
                object obj = ResourceManager.GetObject("world_24_hot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
