using System.Text.RegularExpressions;
using System.Diagnostics;
using System;
using System.Drawing.Drawing2D;
using System.Windows.Forms;
using System.Collections;
using System.Drawing;
using Microsoft.VisualBasic;
using System.Data.SqlClient;
using System.Data;
using System.Collections.Generic;
using WeifenLuo.WinFormsUI;
using Microsoft.Win32;
using WeifenLuo;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace SoftLogik.Win
{
	namespace My
	{
		namespace Resources
		{
			
			
			//This class was auto-generated by the StronglyTypedResourceBuilder
			//class via a tool like ResGen or Visual Studio.
			//To add or remove a member, edit your .ResX file then rerun ResGen
			//with the /str option, or rebuild your VS project.
			///<summary>
			///  A strongly-typed resource class, for looking up localized strings, etc.
			///</summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), global::System.Diagnostics.DebuggerNonUserCodeAttribute(), global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]internal class Strings
			{
				
				
				private static global::System.Resources.ResourceManager resourceMan;
				
				private static global::System.Globalization.CultureInfo resourceCulture;
				
				[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]internal Strings()
				{
				}
				
				///<summary>
				///  Returns the cached ResourceManager instance used by this class.
				///</summary>
				[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]internal static global::System.Resources.ResourceManager ResourceManager
				{
					get
					{
						if (object.ReferenceEquals(resourceMan, null))
						{
							global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftLogik.Win.Strings", typeof(Strings).Assembly);
							resourceMan = temp;
						}
						return resourceMan;
					}
				}
				
				///<summary>
				///  Overrides the current thread's CurrentUICulture property for all
				///  resource lookups using this strongly typed resource class.
				///</summary>
				[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]internal static global::System.Globalization.CultureInfo Culture
				{
					get
					{
						return resourceCulture;
					}
					set
					{
						resourceCulture = value;
					}
				}
				
				///<summary>
				///  Looks up a localized string similar to Auto Hide.
				///</summary>
				internal static string DockPaneCaption_ToolTipAutoHide
				{
					get
					{
						return ResourceManager.GetString("DockPaneCaption_ToolTipAutoHide", resourceCulture);
					}
				}
				
				///<summary>
				///  Looks up a localized string similar to Close.
				///</summary>
				internal static string DockPaneCaption_ToolTipClose
				{
					get
					{
						return ResourceManager.GetString("DockPaneCaption_ToolTipClose", resourceCulture);
					}
				}
				
				///<summary>
				///  Looks up a localized string similar to Window Position.
				///</summary>
				internal static string DockPaneCaption_ToolTipOptions
				{
					get
					{
						return ResourceManager.GetString("DockPaneCaption_ToolTipOptions", resourceCulture);
					}
				}
				
				///<summary>
				///  Looks up a localized string similar to Close.
				///</summary>
				internal static string DockPaneStrip_ToolTipClose
				{
					get
					{
						return ResourceManager.GetString("DockPaneStrip_ToolTipClose", resourceCulture);
					}
				}
				
				///<summary>
				///  Looks up a localized string similar to Active Files.
				///</summary>
				internal static string DockPaneStrip_ToolTipOptions
				{
					get
					{
						return ResourceManager.GetString("DockPaneStrip_ToolTipOptions", resourceCulture);
					}
				}
			}
		}
	}
	
}
